#!/usr/bin/env node
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ENV_DEFAULTS = {
  dev: {
    frontendPort: '5173',
    backendPort: '3000',
    mongoUri: 'mongodb://localhost:27017/developer_tools_portal',
    corsOrigin: 'http://localhost:5173',
    viteApiUrl: 'http://localhost:3000/api',
    seedOnStart: 'true',
  },
  test: {
    frontendPort: '18081',
    backendPort: '19031',
    mongoUri: 'mongodb://mongo:27017/developer_tools_portal_test',
    corsOrigin: 'http://localhost:18081',
    viteApiUrl: 'http://localhost:19031/api',
    seedOnStart: 'true',
  },
  prod: {
    frontendPort: '28080',
    backendPort: '29030',
    mongoUri: 'mongodb://mongo:27017/developer_tools_portal',
    corsOrigin: 'http://localhost:28080',
    viteApiUrl: 'http://localhost:29030/api',
    seedOnStart: 'true',
  },
};

const PROFILE_ALIASES = {
  dev: 'dev',
  develop: 'dev',
  development: 'dev',
  test: 'test',
  stage: 'test',
  staging: 'test',
  prod: 'prod',
  production: 'prod',
};

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');

async function main() {
  let envArgRaw = (process.argv[2] || '').trim();

  if (!envArgRaw) {
    const rootEnvPath = path.join(repoRoot, '.env');
    if (!(await exists(rootEnvPath))) {
      console.error('No .env file at repo root and no env argument provided.');
      usage();
    }

    const rootRaw = await fs.readFile(rootEnvPath, 'utf8');
    const rootValues = parseEnv(rootRaw);
    envArgRaw = (rootValues.get('APP_ENV') || '').trim();

    if (!envArgRaw) {
      console.error('APP_ENV is not set in .env. Set APP_ENV=dev|test|prod.');
      process.exit(1);
    }
  }

  const { sourceFile, profile } = resolveSource(envArgRaw);
  const hasSourceFile = await exists(sourceFile);
  if (!hasSourceFile && !profile) {
    console.error(`Missing ${path.relative(repoRoot, sourceFile)}. Create it from .env.example first.`);
    process.exit(1);
  }

  const raw = hasSourceFile ? await fs.readFile(sourceFile, 'utf8') : '';
  const newline = raw.includes('\r\n') ? '\r\n' : '\n';
  const values = parseEnv(raw);
  const defaultsKey = profile ?? inferDefaultsKey(envArgRaw.toLowerCase());
  const sourceLabel = hasSourceFile ? path.basename(sourceFile) : `${defaultsKey} defaults`;

  await fs.writeFile(path.join(repoRoot, '.env'), buildRootEnv(sourceLabel, defaultsKey, values, newline), 'utf8');
  await fs.writeFile(path.join(repoRoot, 'backend', '.env'), buildBackendEnv(sourceLabel, defaultsKey, values, newline), 'utf8');
  await fs.writeFile(path.join(repoRoot, 'frontend', '.env'), buildFrontendEnv(sourceLabel, defaultsKey, values, newline), 'utf8');

  console.log(`Synced ${sourceLabel} -> .env, backend/.env, frontend/.env`);
}

function usage() {
  console.error('Usage: node scripts/use-env.mjs [dev|test|prod|.env.custom]');
  console.error('Standard profiles use .env.dev/.env.test/.env.prod when present, otherwise built-in defaults.');
  process.exit(1);
}

function resolveSource(envKeyRaw) {
  const envKey = envKeyRaw.trim();
  const envLower = envKey.toLowerCase();
  const profile = PROFILE_ALIASES[envLower];

  if (envKey.startsWith('.env')) {
    const profileFromFileName = profileNameFromEnvFile(envLower);
    return {
      sourceFile: path.resolve(repoRoot, envKey),
      profile: profileFromFileName,
    };
  }
  return {
    sourceFile: path.resolve(repoRoot, `.env.${envKey}`),
    profile,
  };
}

function profileNameFromEnvFile(envFileName) {
  const suffix = envFileName.replace(/^\.env\.?/, '');
  return PROFILE_ALIASES[suffix];
}

function inferDefaultsKey(envArgLower) {
  if (envArgLower.includes('prod')) {
    return 'prod';
  }
  if (envArgLower.includes('test') || envArgLower.includes('stage')) {
    return 'test';
  }
  return 'dev';
}

function parseEnv(raw) {
  const entries = new Map();
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }
    const idx = line.indexOf('=');
    if (idx === -1) {
      continue;
    }
    const key = line.slice(0, idx).trim();
    const value = stripInlineComment(line.slice(idx + 1).trim());
    entries.set(key, value);
  }
  return entries;
}

function stripInlineComment(value) {
  if (value.startsWith('"') || value.startsWith("'")) {
    return value;
  }

  const commentIndex = value.search(/\s#/);
  return commentIndex === -1 ? value : value.slice(0, commentIndex).trimEnd();
}

function buildRootEnv(sourceLabel, defaultsKey, values, newline) {
  const defaults = ENV_DEFAULTS[defaultsKey] ?? ENV_DEFAULTS.dev;
  const lines = [
    `# Generated by scripts/use-env.mjs from ${sourceLabel}`,
    `APP_ENV=${defaultsKey}`,
    '',
    `FRONTEND_PORT=${pick(values, ['FRONTEND_PORT'], defaults.frontendPort)}`,
    `BACKEND_PORT=${pick(values, ['BACKEND_PORT', 'PORT'], defaults.backendPort)}`,
    '',
    `JWT_SECRET=${pick(values, ['JWT_SECRET'], 'change-me')}`,
    `JWT_EXPIRES_IN=${pick(values, ['JWT_EXPIRES_IN'], '1h')}`,
    `CORS_ORIGIN=${pick(values, ['CORS_ORIGIN'], defaults.corsOrigin)}`,
    `VITE_API_URL=${pick(values, ['VITE_API_URL'], defaults.viteApiUrl)}`,
    `SEED_ON_START=${pick(values, ['SEED_ON_START'], defaults.seedOnStart)}`,
    '',
    `ADMIN_EMAIL=${pick(values, ['ADMIN_EMAIL'], 'admin@example.com')}`,
    `ADMIN_PASSWORD=${pick(values, ['ADMIN_PASSWORD'], 'Admin123!')}`,
    `USER_EMAIL=${pick(values, ['USER_EMAIL'], 'user@example.com')}`,
    `USER_PASSWORD=${pick(values, ['USER_PASSWORD'], 'User123!')}`,
  ];

  return ensureTrailingNewline(lines.join(newline), newline);
}

function buildBackendEnv(sourceLabel, defaultsKey, values, newline) {
  const defaults = ENV_DEFAULTS[defaultsKey] ?? ENV_DEFAULTS.dev;
  const lines = [
    `# Generated by scripts/use-env.mjs from ${sourceLabel}`,
    '',
    `PORT=${pick(values, ['PORT', 'BACKEND_INTERNAL_PORT'], '3000')}`,
    `MONGO_URI=${pick(values, ['MONGO_URI'], defaults.mongoUri)}`,
    `JWT_SECRET=${pick(values, ['JWT_SECRET'], 'change-me')}`,
    `JWT_EXPIRES_IN=${pick(values, ['JWT_EXPIRES_IN'], '1h')}`,
    `CORS_ORIGIN=${pick(values, ['CORS_ORIGIN'], defaults.corsOrigin)}`,
    `SEED_ON_START=${pick(values, ['SEED_ON_START'], defaults.seedOnStart)}`,
    '',
    `ADMIN_EMAIL=${pick(values, ['ADMIN_EMAIL'], 'admin@example.com')}`,
    `ADMIN_PASSWORD=${pick(values, ['ADMIN_PASSWORD'], 'Admin123!')}`,
    `USER_EMAIL=${pick(values, ['USER_EMAIL'], 'user@example.com')}`,
    `USER_PASSWORD=${pick(values, ['USER_PASSWORD'], 'User123!')}`,
  ];

  return ensureTrailingNewline(lines.join(newline), newline);
}

function buildFrontendEnv(sourceLabel, defaultsKey, values, newline) {
  const defaults = ENV_DEFAULTS[defaultsKey] ?? ENV_DEFAULTS.dev;
  const lines = [
    `# Generated by scripts/use-env.mjs from ${sourceLabel}`,
    '',
    `VITE_API_URL=${pick(values, ['VITE_API_URL'], defaults.viteApiUrl)}`,
  ];

  return ensureTrailingNewline(lines.join(newline), newline);
}

function pick(values, keys, fallback) {
  for (const key of keys) {
    if (values.has(key)) {
      return values.get(key);
    }
  }
  return fallback;
}

function ensureTrailingNewline(content, newline) {
  return content.endsWith('\n') || content.endsWith('\r\n') ? content : content + newline;
}

async function exists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
